/*
  # Dashboard tables and policies

  1. New tables
    - `bot_guilds`
    - `user_guild_access`
    - `guild_configs`
    - `guild_dashboard_events`
    - `guild_metrics_daily`

  2. Security
    - RLS for dashboard-facing tables
    - helper function `is_manageable_guild`
    - RPC `save_guild_config` for audited writes

  3. Notes
    - `bot_stats` remains public for the landing page
    - `bot_guilds` is maintained by the bot/backend using service role credentials
*/

create extension if not exists pgcrypto;

create or replace function public.set_updated_at_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.bot_guilds (
  guild_id text primary key,
  guild_name text not null,
  guild_icon text,
  member_count bigint default 0,
  premium_tier text default 'free',
  setup_completed boolean default false,
  last_heartbeat_at timestamptz default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.user_guild_access (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  guild_id text not null,
  guild_name text not null,
  guild_icon text,
  permissions_raw text not null default '0',
  can_manage boolean not null default false,
  is_owner boolean not null default false,
  bot_installed boolean not null default false,
  member_count bigint,
  premium_tier text,
  bot_last_seen_at timestamptz,
  last_synced_at timestamptz not null default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, guild_id)
);

create table if not exists public.guild_configs (
  guild_id text primary key references public.bot_guilds(guild_id) on delete cascade,
  general_settings jsonb not null default '{}'::jsonb,
  moderation_settings jsonb not null default '{}'::jsonb,
  dashboard_preferences jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.guild_dashboard_events (
  id uuid primary key default gen_random_uuid(),
  guild_id text not null references public.bot_guilds(guild_id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  title text not null,
  description text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.guild_metrics_daily (
  id bigint generated by default as identity primary key,
  guild_id text not null references public.bot_guilds(guild_id) on delete cascade,
  metric_date date not null default current_date,
  commands_executed bigint not null default 0,
  moderated_messages bigint not null default 0,
  active_members bigint not null default 0,
  uptime_percentage numeric(5,2) not null default 100,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (guild_id, metric_date)
);

drop trigger if exists set_bot_guilds_updated_at on public.bot_guilds;
create trigger set_bot_guilds_updated_at
before update on public.bot_guilds
for each row execute function public.set_updated_at_timestamp();

drop trigger if exists set_user_guild_access_updated_at on public.user_guild_access;
create trigger set_user_guild_access_updated_at
before update on public.user_guild_access
for each row execute function public.set_updated_at_timestamp();

drop trigger if exists set_guild_configs_updated_at on public.guild_configs;
create trigger set_guild_configs_updated_at
before update on public.guild_configs
for each row execute function public.set_updated_at_timestamp();

drop trigger if exists set_guild_metrics_daily_updated_at on public.guild_metrics_daily;
create trigger set_guild_metrics_daily_updated_at
before update on public.guild_metrics_daily
for each row execute function public.set_updated_at_timestamp();

create or replace function public.is_manageable_guild(target_guild_id text)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_guild_access access
    where access.user_id = auth.uid()
      and access.guild_id = target_guild_id
      and access.can_manage = true
  );
$$;

alter table public.bot_guilds enable row level security;
alter table public.user_guild_access enable row level security;
alter table public.guild_configs enable row level security;
alter table public.guild_dashboard_events enable row level security;
alter table public.guild_metrics_daily enable row level security;

drop policy if exists "Users can read own guild access" on public.user_guild_access;
create policy "Users can read own guild access"
  on public.user_guild_access
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Users can read manageable guild configs" on public.guild_configs;
create policy "Users can read manageable guild configs"
  on public.guild_configs
  for select
  to authenticated
  using (public.is_manageable_guild(guild_id));

drop policy if exists "Users can insert manageable guild configs" on public.guild_configs;
create policy "Users can insert manageable guild configs"
  on public.guild_configs
  for insert
  to authenticated
  with check (public.is_manageable_guild(guild_id));

drop policy if exists "Users can update manageable guild configs" on public.guild_configs;
create policy "Users can update manageable guild configs"
  on public.guild_configs
  for update
  to authenticated
  using (public.is_manageable_guild(guild_id))
  with check (public.is_manageable_guild(guild_id));

drop policy if exists "Users can read manageable dashboard events" on public.guild_dashboard_events;
create policy "Users can read manageable dashboard events"
  on public.guild_dashboard_events
  for select
  to authenticated
  using (public.is_manageable_guild(guild_id));

drop policy if exists "Users can insert manageable dashboard events" on public.guild_dashboard_events;
create policy "Users can insert manageable dashboard events"
  on public.guild_dashboard_events
  for insert
  to authenticated
  with check (public.is_manageable_guild(guild_id));

drop policy if exists "Users can read manageable guild metrics" on public.guild_metrics_daily;
create policy "Users can read manageable guild metrics"
  on public.guild_metrics_daily
  for select
  to authenticated
  using (public.is_manageable_guild(guild_id));

create or replace function public.save_guild_config(
  p_guild_id text,
  p_general_settings jsonb,
  p_moderation_settings jsonb,
  p_dashboard_preferences jsonb
)
returns setof public.guild_configs
language plpgsql
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if not public.is_manageable_guild(p_guild_id) then
    raise exception 'You do not have access to this guild';
  end if;

  insert into public.guild_configs (
    guild_id,
    general_settings,
    moderation_settings,
    dashboard_preferences,
    updated_by
  )
  values (
    p_guild_id,
    coalesce(p_general_settings, '{}'::jsonb),
    coalesce(p_moderation_settings, '{}'::jsonb),
    coalesce(p_dashboard_preferences, '{}'::jsonb),
    v_user_id
  )
  on conflict (guild_id) do update
  set
    general_settings = excluded.general_settings,
    moderation_settings = excluded.moderation_settings,
    dashboard_preferences = excluded.dashboard_preferences,
    updated_by = excluded.updated_by,
    updated_at = now();

  insert into public.guild_dashboard_events (
    guild_id,
    actor_user_id,
    event_type,
    title,
    description,
    metadata
  )
  values (
    p_guild_id,
    v_user_id,
    'config_saved',
    'Configuracion actualizada',
    'Se guardaron ajustes generales, moderacion y preferencias del panel.',
    jsonb_build_object(
      'general', true,
      'moderation', true,
      'preferences', true
    )
  );

  return query
  select *
  from public.guild_configs
  where guild_id = p_guild_id;
end;
$$;
